---
abstract: 'Bash completion plugin for vim tags'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.58
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bash-Completion-Plugins-VimTag
no_index:
  directory:
    - t
    - inc
requires:
  Bash::Completion: 0
  Path::Iterator::Rule: 0
  parent: 0
version: 2.00
